# Party-friendly fun facts — edit here, then: python3 scripts/apply-fun-facts.py

FUN_FACTS_BY_TITLE = {
    "Too Tight": "Con Funk Shun's biggest crossover hit — the title is about a relationship that's 'too tight' to walk away from.",
    "Ffun": "The title is spelled F-F-U-N on the record — extra letters for extra funk.",
    "Brick House": "The Commodores' Walter Orange sings the iconic bass-heavy hook on this 1977 smash.",
    "Let It Whip": "Dazz Band won a Grammy for this 1982 synth-funk jam — whip-cracks included.",
    "Reach For It": "George Duke's 1977 instrumental became a breakbeat favorite for DJs and producers.",
    "Back Together Again": "Roberta Flack and Donny Hathaway's final duet before his tragic death in 1979.",
    "Respect": "Aretha flipped Otis Redding's song into a feminist anthem — and spelled R-E-S-P-E-C-T out loud.",
    "Ain't Nobody": "Chaka Khan recorded this with Rufus in one take at a Montreux Jazz Festival soundcheck.",
    "Boogie Wonderland": "Earth, Wind & Fire teamed with The Emotions for this disco-funk floor-filler.",
    "Word Up": "Cameo's codpiece era peaked here — Larry Blackmon's 'ow!' became instant party vocabulary.",
    "Shining Star": "Earth, Wind & Fire wrote this after watching a documentary about the stars in the sky.",
    "Before I Let Go": "Frankie Beverly's live version is the cookout anthem — Maze made it a wedding reception staple.",
    "Joy & Pain": "Maze's signature call-and-response: life is a mix of both, and the crowd always answers.",
    "What's Going On": "Marvin Gaye wrote this after his brother returned from Vietnam — a protest song that still grooves.",
    "Skin Tight": "Ohio Players' suggestive album covers were almost as famous as the funk inside.",
    "Live It Up": "The Isley Brothers' 1978 hit — Ronald Isley's falsetto over that talk-box still slaps.",
    "You Dropped a Bomb on Me": "The Gap Band from Tulsa, Oklahoma — not the clothing store, but just as explosive.",
    "Super Freak": "Rick James wrote this in about an hour — MC Hammer later built 'U Can't Touch This' on the bass line.",
    "Mary Jane": "Rick James' ode to his favorite… herb. The crowd always knows what Mary Jane means.",
    "I Got You (I Feel Good)": "James Brown recorded the definitive version live — one of the most sampled shouts in history.",
    "Fantastic Voyage": "Lakeside's 1980 hit shares its name with a sci-fi movie — the groove is the real trip.",
    "Raid": "Lakeside's slow-burn funk epic — the 'raid' is a heartbreak, not a police bust.",
    "More Bounce to the Ounce": "Zapp & Roger Troutman's talk-box made this 1980 track a West Coast funk blueprint.",
    "We Are Family": "Sister Sledge recorded this in one day — it became the anthem of the 1979 Pittsburgh Pirates.",
    "Square Biz": "Teena Marie rapped on this 1981 track years before rap crossed over to pop radio.",
    "Flash Light": "Parliament's George Clinton and Bootsy Collins — the mothership landed on the dance floor.",
    "I'd Rather Be With You": "Bootsy Collins' 1976 slow jam — Bootsy's star-shaped bass and shades are legendary.",
    "Celebration": "Kool & The Gang wrote this after reading about a global celebration in a magazine.",
    "Lowdown": "Boz Scaggs' Silk Degrees album — David Paich and Jeff Porcaro played on it before forming Toto.",
    "Cut the Cake": "Average White Band's horn section on this 1975 cut is pure Scottish soul — seriously.",
    "Play That Funky Music": "Wild Cherry's one hit was born when a club patron yelled 'play that funky music, white boy!'",
    "Fame": "David Bowie co-wrote this with John Lennon — a gritty NYC anthem from the Young Americans sessions.",
    "The Cisco Kid": "War's 1972 story-song about an outlaw — Low Rider's band keeping the funk west coast.",
    "Minute by Minute": "The Doobie Brothers went full blue-eyed soul — Michael McDonald's voice defined the era.",
    "Bennie and the Jets": "Elton John's glam-rock oddity — the fake live crowd noise was added in the studio.",
    "Don't Go Breaking My Heart": "Elton John and Kiki Dee's 1976 duet — they recorded it in one afternoon.",
    "Babylon Sisters": "Steely Dan's Gaucho album took two years and nearly broke the band — this track was worth it.",
    "Faith": "George Michael's 1987 solo debut sold 25 million copies — the leather jacket era began here.",
    "Get Ready": "Rare Earth stretched this Smokey Robinson cover to 21 minutes live — the crowd never left.",
    "24K Magic": "Bruno Mars channeled '80s Minneapolis funk for this — Prince would have nodded approvingly.",
    "Blame It": "Jamie Foxx ft. T-Pain — the auto-tune anthem of every late-2000s party.",
    "Don't Talk": "Jon B.'s 1995 quiet-storm jam — a slow-dance favorite that still fills the floor.",
    "Boo Thang": "Paul Russell's 2022 viral hit samples 'Just a Friend' — old school meets TikTok.",
    "1999": "Prince said he wrote this forecasting the end of the world — party like it's 1999 anyway.",
    "Little Red Corvette": "Prince's breakthrough pop hit — the car is a metaphor, but the riff is real.",
    "Controversy": "Prince asked 'Am I black or white, am I straight or gay?' in 1981 — ahead of everyone.",
    "Ruff Ryders' Anthem": "DMX's growl on this Swizz Beatz beat announced a new era of hardcore hip-hop.",
    "Changes": "2Pac's posthumous hit samples Bruce Hornsby — a plea for peace that still hits hard.",
    "Rock the Bells": "LL Cool J was 16 when he recorded this — Rick Rubin produced his debut album in his dorm.",
    "Push It": "Salt-N-Pepa's 1987 crossover — 'Push it real good' became an instant call-and-response.",
    "Walk This Way": "Run-D.M.C. and Aerosmith's 1986 mashup broke hip-hop into mainstream radio.",
    "Don't Believe the Hype": "Public Enemy's Chuck D called out the media — still one of rap's greatest slogans.",
    "Summertime": "DJ Jazzy Jeff & The Fresh Prince won the first rap Grammy for this 1991 cookout classic.",
    "Blow the Whistle": "Too $hort's Bay Area anthem — the whistle sound is iconic at every function.",
    "Hot in Herre": "Nelly's 2002 party starter — 'take off all your clothes' was the directive, and crowds obeyed.",
}
